repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: local
    hooks:
    - id: pylint
      name: Linting
      entry: make lint
      language: system
      types: [python]
    - id: pytest
      name: Unit testing
      entry: make test
      language: system
      types: [python]
      always_run: true
      pass_filenames: false
