repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    - id: pylint
      name: Linting
      entry: make lint
      language: system
      types: [python]
    - id: pytest
      name: Unit testing
      entry: make test
      language: system
      types: [python]
