codecov:
  require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: 80
        threshold: 80
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
