codecov:
  require_ci_to_pass: yes
coverage:
  range: "80..100"
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        base: pr
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 80%
        threshold: 0%
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
