version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: web-prod.dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=app
      - DB_DRIVE=mysql+pymysql
      - SLACK_BOT_TOKEN=xoxb-1064441476484-1057682739635-q1JmmBs1BVoevwc5TnqC31DB
      - SLACK_LOG_CHANNEL_ID=C011WCZE3EG
      - CELERY_BROKER_URL=amqp://root:password@rabbitmq:5672/celery
      - CELERY_RESULT_BACKEND=mongodb://root:password@mongodb:27017/celery
    ports:
      - 8000:80
    depends_on:
      - mongodb
      - mysql
      - rabbitmq
    networks:
      - mynet
  worker:
    build:
      context: .
      dockerfile: worker-prod.dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=app
      - DB_DRIVE=mysql+pymysql
      - SLACK_BOT_TOKEN=xoxb-1064441476484-1057682739635-q1JmmBs1BVoevwc5TnqC31DB
      - SLACK_LOG_CHANNEL_ID=C011WCZE3EG
      - CELERY_BROKER_URL=amqp://root:password@rabbitmq:5672/celery
      - CELERY_RESULT_BACKEND=mongodb://root:password@mongodb:27017/celery
    depends_on:
      - mongodb
      - rabbitmq
      - mysql
    networks:
      - mynet
  mysql:
    image: mysql:5.5.61
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - mynet
  rabbitmq:
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=celery
    expose:
      - 5672
    networks:
      - mynet
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=celery
    expose:
      - 27017
    networks:
      - mynet
networks:
  mynet:
