version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          command: make test
          name: Run test
      # - run:
      #     command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
      #     name: Upload codecove report
workflows:
  main:
    jobs:
      - test
