version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip install --user -r requirements-test.txt
          name: Install deps
      - python/save-cache
      - run:
          command: make test
          name: Test

workflows:
  main:
    jobs:
      - test
