version: 2.1

jobs:
  test:
    steps:
      - checkout
      - set_remote_docker:
          docker_layer_caching: true
      - run:
          command: make test
      # - run:
      #     command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
      #     name: Upload codecove report
workflows:
  main:
    jobs:
      - test
